# Generated by Django 2.1.1 on 2018-10-03 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='meetup.Interest'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='interests',
        ),
        migrations.AddField(
            model_name='group',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='meetup.Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
